name: Build FlyJB X
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      -
        name: Multiple Checkout
        uses: vweevers/multi-checkout-action@v1
        with:
          repositories: |
            jmpews/Dobby
            hekatos/FlyJB-X
      - 
        name: Setup Procursus
        uses: beerpiss/procursus-action@v1.1
        with:
          packages: clang cmake ldid make
      -
        name: Setup Theos
        run: |
          echo "THEOS=$GITHUB_WORKSPACE/theos" >> $GITHUB_ENV
          git clone https://github.com/theos/theos ${{ github.workspace }}/theos --recursive
          
          curl -sLO https://github.com/theos/sdks/archive/master.zip
          TMP=$(mktemp -d)
          7z x master.zip -o$TMP
          mv $TMP/*-master/*.sdk $THEOS/sdks
          rm -r master.zip $TMP

          ls -lha $THEOS/sdks
      - 
        name: Prep for iOS 14.5 SDK
        run: |
          sudo xcode-select --switch /Applications/Xcode_13.2.1.app
          defaults write /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Info.plist MinimumSDKVersion 14.5
      - 
        name: Build Dobby
        run: |
          (
            cd ../jmpews/Dobby
            mkdir build
            cd build
            
            cmake -D CMAKE_C_COMPILER="/opt/procursus/bin/clang" \
              -D CMAKE_CXX_COMPILER="/opt/procursus/bin/clang++" \
              -D CMAKE_OSX_SYSROOT="/Users/runner/work/FlyJB-X/FlyJB-X/theos/sdks/iPhoneOS14.5.sdk" \
              -G Xcode .. -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_SYSTEM_PROCESSOR=arm64 -DCMAKE_OSX_DEPLOYMENT_TARGET=9.3
            xcodebuild ARCHS="armv7 arm64 arm64e" ONLY_ACTIVE_ARCH=NO -scheme DobbyX -configuration Release -sdk iphoneos14.5 archive -archivePath build.xcarchive
            cp -r build.xcarchive/Products/@rpath/DobbyX.framework $THEOS/lib/
          )
      -
        name: Build tweak
        run: gmake -C ../hekatos/FlyJB-X all
        


